[package]
name = "ragent_test"
version = "0.1.0"
edition = "2021"

[dependencies]
ragent = { path = "../ragent" }
serde = "1.0.217"
serde_json = "1.0.135"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
